---
title: "main"
output: html_document
---


```{r}
pacman::p_load(tidyverse, 
               dplyr, 
               readxl, 
               ggplot2)
```

# Base de datos
```{r message=FALSE, warning=FALSE}
data <- read_csv("data/aircrahesFullDataUpdated_2024.csv")
names(data)[11] <- "Fatalities"
data <- data %>% mutate(all_fatal = Ground + Fatalities,
                        tasa_muertes = Fatalities / Aboard)
data <- data[data$tasa_muertes != Inf, ]
data <- data[!is.na(data$tasa_muertes), ]
```

# Análisis exploratorio de datos

## Aeronaves con mayor cantidad de accidentes
```{r}
data %>% 
  count(Aircraft, sort = TRUE) %>% 
  slice_max(n, n = 20) %>% 
  ggplot(aes(x = reorder(Aircraft, n), y = n)) +
  geom_col(fill = 'lightblue4') +
  coord_flip() +
  labs(x = "Aeronave", y = "Frecuencia") +
  theme_minimal()
```

## Aeronaves con mayor cantidad de accidentes generalizada al fabricante 
```{r}
data %>% 
  count(`Aircraft Manufacturer`, sort = TRUE) %>% 
  slice_max(n, n= 15) %>% 
  ggplot(aes(x = reorder(`Aircraft Manufacturer`, n), y = n)) +
  geom_col(fill = 'lightblue4') +
  coord_flip() +
  labs(x = "Fabricante", y = "Frecuencia") +
  theme_minimal()
```

## Cantidad de accidentes por año
```{r}
data %>%
  count(Year) %>%
  ggplot(aes(x = Year, y = n)) +
  geom_line(color = "lightblue4", size = 0.75) +
  labs(x = "Año", y = "Cantidad de accidentes") +
  theme_minimal()
```

## Cantidad de accidentes por país/región
```{r}
data %>%
  filter(!is.na(`Country/Region`), `Country/Region` != "N/A") %>%
  count(`Country/Region`, sort = T) %>%
  slice_max(n, n = 20) %>%
  ggplot(aes(x = reorder(`Country/Region`, n), y = n)) +
  geom_col(fill = 'lightblue4') +
  coord_flip() +
  labs(x = "País/Región", y = "Frecuencia") +
  theme_minimal()
```

## Distribución muertes a bordo
```{r}
data %>%
  ggplot(aes(x = Fatalities)) +
  geom_histogram(binwidth = 5,
                 fill = "lightblue4",
                 color = "black") +
  labs(x = "Fatalities", y = "Frecuencia") +
  theme_minimal()
```

## Distribución de la tasa de muertes

```{r}
data %>%
  ggplot(aes(x = tasa_muertes)) +
    geom_histogram(binwidth = 0.05,
                 fill = "lightblue4",
                 color = "black") +
  labs(x = "Tasa de muertes", y = "Frecuencia") +
  theme_minimal()
```

## Severidad relativa del accidente
```{r}
data %>%
  ggplot(aes(x = Aboard, y = Fatalities, color = tasa_muertes)) +
  geom_point(alpha = 0.75, size = 2) +
  geom_abline(
    slope = 1,
    intercept = 0,
    linetype = "dashed",
    color = "red",
    alpha = 0.5
  ) +
  scale_color_gradient(low = "lightblue", high = "darkred") +
  labs(x = "Pasajeros a bordo", y = "Muertes", color = "Tasa de muertes") +
  theme_minimal()
```

# GLM
```{r}
data <- data %>%
  mutate(Operator = case_when(
    str_detect(tolower(Operator), "air") ~ "Comercial",
    str_detect(tolower(Operator), "military|force|navy") ~ "Militar",
    TRUE ~ "Otro"
  ))
```


```{r}
mod.poisson <- glm(Fatalities ~ Operator, 
                      data = data, family = poisson)
summary(mod.poisson)
```

```{r}
dispersion <- sum(residuals(mod.poisson, type = "pearson")^2) / df.residual(mod.poisson)
dispersion
```


```{r}
library(MASS)
modelo_nb <- glm.nb(Fatalities ~ Operator, data = data)
summary(modelo_nb)
```

# Primas

```{r}
data <- data %>% mutate(
  costo_aviones = 100e6 * 1.05**(-(2024-data$Year)),
  costo_vidas = data$Fatalities * 2.1e6 * 1.05**(-(2024-data$Year))
)

qx <- sum(data$Year == 2024)/1e6 # 43.8e6
mean_fatal <- mean(data$Fatalities,na.rm = T)

# Costo de asegurar un avión a 100 años

ins_aviones <- sum(sapply(1:100, function(x) qx*(1-qx)**(x-1)*100e6*1.05**(-x+1)))


# Costo de asegurar las personas que mueren en el avión a 100 años

ins_vidas <- sum(sapply(1:100, function(x) qx*(1-qx)**(x-1)*mean_fatal*2.1e6*1.05**(-x+1)))

# Prima nivelada

an <- (1-1.05^-100)/0.05
(prima <- (ins_aviones+ins_vidas)/an)
```


